imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\Admin
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

easy_admin:
    site-name: "CarcassonneImmo"
    design:
        menu:
            - { entity: 'Admin', icon: 'user' }
            - { entity: 'Annonces', icon: 'buysellads' }
            - { entity: 'Client', icon: 'address-card' }
            - { entity: 'TypeAnnonce', icon: 'folder-open' }
    entities:
    
        Annonces:
            class: AppBundle\Entity\Annonce
            label: 'Annonces'
            form:
                fields:
                    - titre
                    - photo
                    - { property: 'nbPiece', label: "Nombre de pièces"}
                    - prix
                    - telephone
                    - description
                    - { property: 'cliOid', label: "Propriétaire"}
                    - { property: 'admOid', label: "Créateur de l'annonce"}
                    - { property: 'typOid', label: "Type d'annonce"}
            list:
                fields:
                    - titre
                    - photo
                    - nbPiece
        Admin:
            class: AppBundle\Entity\Admin
            label: 'Employés'
            form:
            # Affichage du formulaire d'édition
                fields:
                    - { type: 'group', css_class: 'col-sm-4', label: 'Informations de base' }
                    - nom
                    - prenom
                    - telephone
                    - { type: 'group', css_class: 'col-sm-8', label: 'Identifiants' }
                    - email
                    - { property: 'username', label: "Nom d'utilisateur"}
                    - { property: 'plainPassword', label: "Mot de passe", type: 'text', type_options: { required: false } }
                    - { type: 'group', css_class: 'col-sm-12', help: 'Administration' }
                    - { property: 'enabled', label: 'Activation du compte'}
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: {'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            # Affichage de la liste des entrées 
            list:
                fields:
                    - username
                    - nom
                    - prenom
                    - email
                    - { property: 'enabled', label: 'Activation du compte'}
                    - { property: 'lastLogin', label: 'Dernière connexion'}
        Client:
            class: AppBundle\Entity\Client
            label: 'Clients'
            form:
            # Affichage du formulaire d'édition
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: 'Informations du client' }
                    - prenom
                    - nom
                    - telephone
            # Affichage de la liste des entrées 
            list:
                fields:
                    - nom
                    - prenom
                    - telephone
        TypeAnnonce:
            class: AppBundle\Entity\TypeAnnonce
            label: "Type d'annonces"
            form:
            # Affichage du formulaire d'édition
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: 'Informations du client' }
                    - nom
            # Affichage de la liste des entrées 
            list:
                fields:
                    - nom